##### Reload config #####
unbind r
bind r source-file ~/.tmux.conf \; display "tmux reloaded"

##### Prefix #####
set -g prefix C-a

##### Core #####
set -g mouse on
set-option -g status-position top

set -g default-terminal "tmux-256color"

set -g base-index 1
setw -g pane-base-index 1

set -g automatic-rename off
set -g allow-rename off

##### Catppuccin options (BEFORE plugins load) #####
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_status_left_separator  ""
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_pane_active_border_style "fg=#a87f79"

set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_default_text " #W"

# Options: single, double, heavy, simple, number
set -g pane-border-lines heavy

##### Status line #####
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""

set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

##### TPM plugins #####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'

##### TPM bootstrap (MUST be last) #####
run '~/.tmux/plugins/tpm/tpm'
